//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace P3Image.DataAcces
{
    using System;
    using System.Collections.Generic;
    
    public partial class Campo
    {
        public Campo()
        {
            this.Valores = new HashSet<CampoValor>();
        }
    
        public int Id { get; set; }
        public string Descricao { get; set; }
        public int TipoId { get; set; }
        public int SubCategoriaId { get; set; }
    
        public virtual SubCategoria SubCategoria { get; set; }
        public virtual TipoCampo TipoCampo { get; set; }
        public virtual ICollection<CampoValor> Valores { get; set; }
    }
}
